/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CafeCafeIdRouteImport } from './routes/cafe.$cafeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeCafeIdRoute = CafeCafeIdRouteImport.update({
  id: '/cafe/$cafeId',
  path: '/cafe/$cafeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cafe/$cafeId': typeof CafeCafeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cafe/$cafeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cafe/$cafeId'
  id: '__root__' | '/' | '/cafe/$cafeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafeCafeIdRoute: typeof CafeCafeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/$cafeId': {
      id: '/cafe/$cafeId'
      path: '/cafe/$cafeId'
      fullPath: '/cafe/$cafeId'
      preLoaderRoute: typeof CafeCafeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafeCafeIdRoute: CafeCafeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
